version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:stretch-scm
    working_directory: ~/app
    steps:
      - checkout
      - run:
          command: | 
            curl -H "Content-Type: application/json" --data '{"build": true}' https://registry.hub.docker.com/u/classmethod/docker-schemaspy/trigger/$TOKEN
workflows:
  version: 2
  all:
    jobs:
      - build 
  scheduled:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master

    jobs:
      - build